name: Docker Build and Push

on:
  push:
    branches: [ "main" ]
    # Temporarily remove paths to test
    # paths:
    #   - 'backend/**'
    #   - 'mobile/**'
    #   - '.github/workflows/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
        # Continue on error to see subsequent steps
        continue-on-error: true

      - name: Debug Docker Hub Login
        run: |
          echo "Checking Docker login status"
          docker info | grep Username
          echo "Docker Hub Username: ${{ secrets.DOCKER_HUB_USERNAME }}"

      - name: Build and Push Backend
        run: |
          echo "Building backend image..."
          docker build -t jarintasnim63/agrolink-backend:latest ./backend
          echo "Pushing backend image..."
          docker push jarintasnim63/agrolink-backend:latest || echo "Push failed"

      - name: Build and Push Mobile
        run: |
          echo "Building mobile image..."
          docker build -t jarintasnim63/agrolink-mobile:latest ./mobile
          echo "Pushing mobile image..."
          docker push jarintasnim63/agrolink-mobile:latest || echo "Push failed"
